server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:data
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true

debug: true

logging:
  level:
    org.springframework.security.web: DEBUG